FROM python:3.10.6-slim-buster

RUN pip install --upgrade pip

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .


COPY ./entrypoint.sh .
RUN chmod +x /app/entrypoint.sh
CMD ["sh", "/app/entrypoint.sh"]
