version: '3.8'

services:
  pgdb:
    image: postgres:14.4-alpine
    container_name: local_pgdb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init_scripts:/docker-entrypoint-initdb.d
    env_file:
      - .env.db
  minio:
    build: ./minio
    volumes:
      - ~/minio/data:/data
  backend:
    build: ./backend
    volumes:
      - static:/app/static
      - templates:/app/templates
    env_file:
      - .env
    depends_on:
      - pgdb
      - minio
  frontend:
    build: ./frontend
    volumes:
      - frontend:/app
  nginx:
    build: ./nginx
    volumes:
      - static:/backend/static
      - templates:/backend/templates
      - frontend:/var/www/frontend
    ports:
      - "1337:1337"
    depends_on:
      - backend
      - frontend
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    env_file:
      - .env.db


volumes:
  static:
  templates:
  frontend:
  postgres_data: