# Generated by Django 5.0.3 on 2024-09-10 07:30

import IEF.base_model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=128, verbose_name='Код списка')),
                ('code', models.CharField(max_length=128, verbose_name='Код элемента')),
                ('short_name', models.JSONField(default=IEF.base_model.default_map, verbose_name='Краткое наименование')),
                ('full_name', models.JSONField(blank=True, default=IEF.base_model.default_map, null=True, verbose_name='Полное наименование')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Перечисление',
                'verbose_name_plural': 'Перечисления',
            },
        ),
    ]
