# Generated by Django 5.0.3 on 2024-10-16 10:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import pfbase.base_models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.JSONField(verbose_name='Краткое наименование')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
                'db_table': '"dcm"."idc_parameter"',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=pfbase.base_models.default_map, verbose_name='Наименование организации')),
                ('identifier', models.CharField(blank=True, max_length=128, null=True, verbose_name='БИН')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SYS Организация',
                'verbose_name_plural': 'SYS Организации',
                'db_table': '"sys"."organization"',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users', verbose_name='Фото профиля')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_organization', to='pfbase.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'SYS Пользователь',
                'verbose_name_plural': 'SYS Пользователи',
                'db_table': '"sys"."user"',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ABCDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=pfbase.base_models.default_map, verbose_name='Наименование')),
                ('description', models.JSONField(blank=True, default=pfbase.base_models.default_map, null=True, verbose_name='Описание')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='Код')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'DCT Справочник',
                'verbose_name_plural': 'DCT Справочники',
                'db_table': '"dct"."abc_dictionary"',
            },
        ),
        migrations.CreateModel(
            name='ABCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=pfbase.base_models.default_map, verbose_name='Наименование')),
                ('description', models.JSONField(blank=True, default=pfbase.base_models.default_map, null=True, verbose_name='Описание')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='Код')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pfbase.abcdocument', verbose_name='Родительский элемент')),
            ],
            options={
                'verbose_name': 'DCM Документ',
                'verbose_name_plural': 'DCM Документы',
                'db_table': '"dcm"."abc_document"',
            },
        ),
        migrations.CreateModel(
            name='DctIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=pfbase.base_models.default_map, verbose_name='Наименование')),
                ('description', models.JSONField(blank=True, default=pfbase.base_models.default_map, null=True, verbose_name='Описание')),
                ('index_sort', models.PositiveIntegerField(blank=True, unique=True, verbose_name='Индекс сортировки')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='Код')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Активный')),
                ('type_value', models.CharField(choices=[('str', 'string'), ('int', 'integer'), ('float', 'float'), ('bool', 'boolean'), ('list', 'list'), ('datetime', 'datetime'), ('date', 'date'), ('time', 'time'), ('text', 'text'), ('file', 'file'), ('enum', 'enum'), ('dct', 'dictionary'), ('dcm', 'document'), ('calc', 'calculate')], default='str', max_length=64, verbose_name='Тип')),
                ('type_extend', models.CharField(blank=True, max_length=128, null=True, verbose_name='Тип расширения')),
                ('abc_dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator', to='pfbase.abcdictionary', verbose_name='Справочник')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='pfbase.abcdictionary', verbose_name='Внешний ключ')),
            ],
            options={
                'verbose_name': 'DCT Индикатор',
                'verbose_name_plural': 'DCT Индикаторы',
                'db_table': '"dct"."dct_indicator"',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.JSONField(default=pfbase.base_models.default_map, verbose_name='Краткое наименование')),
                ('full_name', models.JSONField(blank=True, default=pfbase.base_models.default_map, null=True, verbose_name='Краткое наименование')),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='Код')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('abc_dictionary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfbase.abcdictionary', verbose_name='Справочник')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='element', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pfbase.element', verbose_name='Родительский элемент')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='element', to='pfbase.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'DCT Элемент',
                'verbose_name_plural': 'DCT Элементы',
                'db_table': '"dct"."element"',
            },
        ),
        migrations.CreateModel(
            name='ElementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.JSONField(blank=True, null=True, verbose_name='Слепок')),
                ('action', models.CharField(blank=True, max_length=128, null=True, verbose_name='Действие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='element_history', to='pfbase.element', verbose_name='Элемент')),
            ],
            options={
                'verbose_name': 'DCT История элемента',
                'verbose_name_plural': 'DCT История элементов',
                'db_table': '"dct"."element_history"',
            },
        ),
        migrations.CreateModel(
            name='ElementIndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_int', models.IntegerField(blank=True, null=True, verbose_name='Целое число')),
                ('value_str', models.CharField(blank=True, max_length=255, null=True, verbose_name='Строка')),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('value_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время')),
                ('value_bool', models.BooleanField(blank=True, null=True, verbose_name='Логическое значение')),
                ('value_reference', models.PositiveIntegerField(blank=True, null=True, verbose_name='Внешний ключ')),
                ('index_sort', models.PositiveIntegerField(blank=True, unique=True, verbose_name='Индекс сортировки')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Активный')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_value', to='pfbase.element', verbose_name='Элемент')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_value', to='pfbase.dctindicator', verbose_name='Показатель')),
            ],
            options={
                'verbose_name': 'DCT Значение инициатора',
                'verbose_name_plural': 'DCT Значение индикаторов',
                'db_table': '"dct"."indicator_value"',
            },
        ),
        migrations.CreateModel(
            name='DcmIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=pfbase.base_models.default_map, verbose_name='Наименование')),
                ('description', models.JSONField(blank=True, default=pfbase.base_models.default_map, null=True, verbose_name='Описание')),
                ('index_sort', models.PositiveIntegerField(blank=True, unique=True, verbose_name='Индекс сортировки')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='Код')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Активный')),
                ('type_value', models.CharField(choices=[('str', 'string'), ('int', 'integer'), ('float', 'float'), ('bool', 'boolean'), ('list', 'list'), ('datetime', 'datetime'), ('date', 'date'), ('time', 'time'), ('text', 'text'), ('file', 'file'), ('enum', 'enum'), ('dct', 'dictionary'), ('dcm', 'document'), ('calc', 'calculate')], default='str', max_length=64, verbose_name='Тип')),
                ('type_extend', models.CharField(blank=True, max_length=128, null=True, verbose_name='Тип расширения')),
                ('custom_rule', models.JSONField(blank=True, null=True, verbose_name='Правило')),
                ('reference', models.PositiveIntegerField(blank=True, null=True, verbose_name='Внешний ключ')),
                ('abc_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator', to='pfbase.abcdocument', verbose_name='Документ')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parameters', models.ManyToManyField(blank=True, to='pfbase.indicatorparameter', verbose_name='Параметры')),
            ],
            options={
                'verbose_name': 'DCM Индикатор',
                'verbose_name_plural': 'DCM Индикаторы',
                'db_table': '"dcm"."dcm_indicator"',
            },
        ),
        migrations.CreateModel(
            name='PFEnum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.CharField(max_length=128, verbose_name='Код списка')),
                ('code', models.CharField(max_length=128, verbose_name='Код элемента')),
                ('short_name', models.JSONField(default=pfbase.base_models.default_map, verbose_name='Краткое наименование')),
                ('full_name', models.JSONField(blank=True, default=pfbase.base_models.default_map, null=True, verbose_name='Полное наименование')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enum', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'SYS Перечисление',
                'verbose_name_plural': 'SYS Перечисления',
                'db_table': '"sys"."pf_enum"',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('abc_document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfbase.abcdocument', verbose_name='Документ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record', to='pfbase.organization', verbose_name='Организация')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pfbase.record', verbose_name='Родительский элемент')),
            ],
            options={
                'verbose_name': 'DCM Запись документа',
                'verbose_name_plural': 'DCM Записи документов',
                'db_table': '"dcm"."record"',
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(auto_now=True, null=True)),
                ('type_notification', models.CharField(choices=[('info', 'INFO'), ('warning', 'WARNING'), ('reminder', 'REMINDER'), ('error', 'ERROR')], default='info', max_length=20, verbose_name='Тип уведомления')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_source', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pfbase.record', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'SYS Уведомление',
                'verbose_name_plural': 'SYS Уведомления',
                'db_table': '"sys"."notification"',
            },
        ),
        migrations.CreateModel(
            name='RecordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='created', max_length=28, verbose_name='Статус')),
                ('status_comment', models.TextField(blank=True, max_length=312, null=True, verbose_name='Комментарий')),
                ('stage', models.CharField(blank=True, max_length=128, null=True, verbose_name='Этап')),
                ('action', models.CharField(blank=True, max_length=128, null=True, verbose_name='Действие')),
                ('signature', models.BooleanField(blank=True, null=True, verbose_name='Подписание')),
                ('sign_stamp', models.TextField(blank=True, null=True, verbose_name='Ключ верификации')),
                ('stamp', models.JSONField(blank=True, null=True, verbose_name='Слепок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_history', to='pfbase.record', verbose_name='Журнал документа')),
            ],
            options={
                'verbose_name': 'DCM История записи',
                'verbose_name_plural': 'DCM Истории записей',
                'db_table': '"dcm"."record_history"',
            },
        ),
        migrations.CreateModel(
            name='RecordIndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_int', models.IntegerField(blank=True, null=True, verbose_name='Целое число')),
                ('value_str', models.CharField(blank=True, max_length=255, null=True, verbose_name='Строка')),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('value_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время')),
                ('value_bool', models.BooleanField(blank=True, null=True, verbose_name='Логическое значение')),
                ('value_reference', models.PositiveIntegerField(blank=True, null=True, verbose_name='Внешний ключ')),
                ('index_sort', models.PositiveIntegerField(blank=True, unique=True, verbose_name='Индекс сортировки')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Активный')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_value', to='pfbase.dcmindicator', verbose_name='Показатель')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_value', to='pfbase.record', verbose_name='Запсиь')),
            ],
            options={
                'verbose_name': 'DCM Значение инидкатора',
                'verbose_name_plural': 'DCM Значения индикаторов',
                'db_table': '"dcm"."indicator_value"',
            },
        ),
    ]
