# Generated by Django 5.1.2 on 2024-11-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfbase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='records',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_blocked',
        ),
        migrations.AddField(
            model_name='dcmindicators',
            name='is_filtered',
            field=models.BooleanField(blank=True, default=False, verbose_name='Добавить в фильтр'),
        ),
        migrations.AddField(
            model_name='dctindicators',
            name='is_filtered',
            field=models.BooleanField(blank=True, default=False, verbose_name='Добавить в фильтр'),
        ),
        migrations.AddField(
            model_name='listvalues',
            name='index_sort',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Индекс сортировки'),
        ),
        migrations.AddField(
            model_name='recordhistory',
            name='comment',
            field=models.TextField(blank=True, max_length=900, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Фото профиля'),
        ),
    ]
