# Generated by Django 5.1.2 on 2024-10-28 17:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfbase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elementhistory',
            name='status_enum',
        ),
        migrations.RemoveField(
            model_name='elementhistory',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='recordhistory',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='recordhistory',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='recordhistory',
            name='status_comment',
        ),
        migrations.RemoveField(
            model_name='recordhistory',
            name='status_list',
        ),
        migrations.AddField(
            model_name='dcmindicators',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dcmindicators',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dcmindicators',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dctindicators',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dctindicators',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dctindicators',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dictionaries',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dictionaries',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dictionaries',
            name='type',
            field=models.CharField(choices=[('main', 'Main'), ('sub', 'Sub')], default='main', max_length=4, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='dictionaries',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='type',
            field=models.CharField(choices=[('main', 'Main'), ('sub', 'Sub')], default='main', max_length=4, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='documents',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='elementhistory',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfbase.listvalues', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='elementindicatorvalues',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elementindicatorvalues',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elementindicatorvalues',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='elements',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='elements',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elements',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listvalues',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listvalues',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listvalues',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='recordindicatorvalues',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recordindicatorvalues',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recordindicatorvalues',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='records',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dcmindicators',
            name='type_value',
            field=models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean'), ('list', 'List'), ('datetime', 'Datetime'), ('date', 'Date'), ('time', 'Time'), ('text', 'Text'), ('file', 'File'), ('dct', 'Dictionary'), ('dcm', 'Document'), ('calc', 'Calculate'), ('user', 'User'), ('org', 'Organization')], default='str', max_length=64, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='dctindicators',
            name='type_value',
            field=models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean'), ('list', 'List'), ('datetime', 'Datetime'), ('date', 'Date'), ('time', 'Time'), ('text', 'Text'), ('file', 'File'), ('dct', 'Dictionary'), ('dcm', 'Document'), ('calc', 'Calculate'), ('user', 'User'), ('org', 'Organization')], default='str', max_length=64, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='elementhistory',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], default='create', max_length=6, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='recordhistory',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], default='create', max_length=10, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='recordhistory',
            name='sign_stamp',
            field=models.TextField(blank=True, null=True, verbose_name='Слепок подписания'),
        ),
        migrations.AlterField(
            model_name='recordhistory',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pfbase.listvalues', verbose_name='Статус'),
        ),
    ]
