# Generated by Django 5.1.2 on 2025-01-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfbase', '0002_update_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='index_sort',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Индекс сортировки'),
        ),
    ]
