# Generated by Django 5.1.2 on 2025-02-06 11:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfbase', '0003_documents_index_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcmindicators',
            name='is_multiple',
            field=models.BooleanField(blank=True, default=False, verbose_name='Множественный выбор'),
        ),
        migrations.AddField(
            model_name='dctindicators',
            name='is_multiple',
            field=models.BooleanField(blank=True, default=False, verbose_name='Множественный выбор'),
        ),
        migrations.AddField(
            model_name='elementindicatorvalues',
            name='value_array_int',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, size=None, verbose_name='Список Int'),
        ),
        migrations.AddField(
            model_name='elementindicatorvalues',
            name='value_array_str',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None, verbose_name='Список Str'),
        ),
        migrations.AddField(
            model_name='elements',
            name='index_sort',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Индекс сортировки'),
        ),
        migrations.AddField(
            model_name='recordindicatorvalues',
            name='value_array_int',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, default=list, size=None, verbose_name='Список Int'),
        ),
        migrations.AddField(
            model_name='recordindicatorvalues',
            name='value_array_str',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, default=list, size=None, verbose_name='Список Str'),
        ),
    ]
