# Generated by Django 5.1.2 on 2025-02-28 15:14

import pfbase.config
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfbase', '0004_migrations_ismultiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcmindicators',
            name='is_required',
            field=models.BooleanField(blank=True, default=False, verbose_name='Обязательное поле'),
        ),
        migrations.AddField(
            model_name='dctindicators',
            name='is_required',
            field=models.BooleanField(blank=True, default=False, verbose_name='Обязательное поле'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.JSONField(blank=True, default=pfbase.config.default_name, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.JSONField(blank=True, default=pfbase.config.default_name, verbose_name='Заголовок'),
        ),
    ]
