# Generated by Django 5.1.2 on 2025-05-05 11:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfbase', '0005_dcmindicators_is_required_dctindicators_is_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcmindicators',
            name='type_value',
            field=models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean'), ('list', 'List'), ('datetime', 'Datetime'), ('date', 'Date'), ('time', 'Time'), ('text', 'Text'), ('file', 'File'), ('json', 'Json'), ('dct', 'Dictionary'), ('dcm', 'Document'), ('calc', 'Calculate'), ('user', 'User'), ('org', 'Organization'), ('list_integers', 'List Integers'), ('list_string', 'List String')], default='str', max_length=64, verbose_name='Тип значения'),
        ),
        migrations.AlterField(
            model_name='dctindicators',
            name='type_value',
            field=models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean'), ('list', 'List'), ('datetime', 'Datetime'), ('date', 'Date'), ('time', 'Time'), ('text', 'Text'), ('file', 'File'), ('json', 'Json'), ('dct', 'Dictionary'), ('dcm', 'Document'), ('calc', 'Calculate'), ('user', 'User'), ('org', 'Organization'), ('list_integers', 'List Integers'), ('list_string', 'List String')], default='str', max_length=64, verbose_name='Тип значения'),
        ),
        migrations.AlterField(
            model_name='elementindicatorvalues',
            name='value_array_str',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Список Str'),
        ),
        migrations.AlterField(
            model_name='recordindicatorvalues',
            name='value_array_str',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None, verbose_name='Список Str'),
        ),
    ]
