# Generated by Django 5.1.2 on 2025-06-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfbase', '0006_alter_dcmindicators_type_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='index_sort',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Индекс сортировки'),
        ),
    ]
