# Generated by Django 5.0.3 on 2024-09-10 07:30

import IEF.base_model
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=IEF.base_model.default_map, verbose_name='Наименование')),
                ('description', models.JSONField(blank=True, default=IEF.base_model.default_map, null=True, verbose_name='Описание')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'db_table': '"dcm"."abc_document"',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=IEF.base_model.default_map, verbose_name='Наименование')),
                ('description', models.JSONField(blank=True, default=IEF.base_model.default_map, null=True, verbose_name='Описание')),
                ('index_sort', models.PositiveIntegerField(blank=True, unique=True, verbose_name='Индекс сортировки')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='Код')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Активный')),
                ('type_value', models.CharField(choices=[('str', 'string'), ('int', 'integer'), ('float', 'float'), ('bool', 'boolean'), ('list', 'list'), ('datetime', 'datetime'), ('date', 'date'), ('time', 'time'), ('text', 'text'), ('file', 'file'), ('enum', 'enum'), ('dct', 'dictionary'), ('dcm', 'document'), ('calc', 'calculate')], default='str', max_length=64, verbose_name='Тип')),
                ('type_extend', models.CharField(blank=True, max_length=128, null=True, verbose_name='Тип расширения')),
                ('custom_rule', models.JSONField(blank=True, null=True, verbose_name='Правило')),
                ('reference', models.PositiveIntegerField(blank=True, null=True, verbose_name='Внешний ключ')),
            ],
            options={
                'verbose_name': 'Индикатор',
                'verbose_name_plural': 'Индикаторы',
                'db_table': '"dcm"."indicator"',
            },
        ),
        migrations.CreateModel(
            name='IndicatorParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.JSONField(verbose_name='Краткое наименование')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
                'db_table': '"dcm"."idc_parameter"',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Запись документа',
                'verbose_name_plural': 'Записи документов',
                'db_table': '"dcm"."record"',
            },
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RecordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Создан'), ('SIGNED', 'Подписан'), ('CANCELED', 'Отменен')], default='CREATED', max_length=28, verbose_name='Статус')),
                ('status_comment', models.TextField(blank=True, max_length=312, null=True, verbose_name='Комментарий')),
                ('stage', models.CharField(blank=True, max_length=128, null=True, verbose_name='Этап')),
                ('action', models.CharField(blank=True, max_length=128, null=True, verbose_name='Действие')),
                ('signature', models.BooleanField(blank=True, null=True, verbose_name='Подписание')),
                ('sign_stamp', models.TextField(blank=True, null=True, verbose_name='Ключ верификации')),
                ('stamp', models.JSONField(blank=True, null=True, verbose_name='Слепок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'История записи',
                'verbose_name_plural': 'Истории записей',
                'db_table': '"dcm"."record_history"',
            },
        ),
        migrations.CreateModel(
            name='RecordIndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_int', models.IntegerField(blank=True, null=True, verbose_name='Целое число')),
                ('value_str', models.CharField(blank=True, max_length=255, null=True, verbose_name='Строка')),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('value_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время')),
                ('value_bool', models.BooleanField(blank=True, null=True, verbose_name='Логическое значение')),
                ('value_reference', models.PositiveIntegerField(blank=True, null=True, verbose_name='Внешний ключ')),
                ('index_sort', models.PositiveIntegerField(blank=True, unique=True, verbose_name='Индекс сортировки')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Значение инидкатора',
                'verbose_name_plural': 'Значения индикаторов',
                'db_table': '"dcm"."indicator_value"',
            },
        ),
    ]
