# Generated by Django 5.0.3 on 2024-09-10 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abcdocument',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='abc_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator', to='documents.abcdocument', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='parameters',
            field=models.ManyToManyField(blank=True, to='documents.indicatorparameter', verbose_name='Параметры'),
        ),
        migrations.AddField(
            model_name='record',
            name='abc_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.abcdocument', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='record',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='record',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='documents.record', verbose_name='Родительский элемент'),
        ),
        migrations.AddField(
            model_name='recordhistory',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='recordhistory',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='record_history', to='documents.record', verbose_name='Журнал документа'),
        ),
        migrations.AddField(
            model_name='recordindicatorvalue',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_value', to='documents.indicator', verbose_name='Показатель'),
        ),
        migrations.AddField(
            model_name='recordindicatorvalue',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record_value', to='documents.record', verbose_name='Запсиь'),
        ),
    ]
