# Generated by Django 5.0.3 on 2024-09-10 07:30

import IEF.base_model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABCDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=IEF.base_model.default_map, verbose_name='Наименование')),
                ('description', models.JSONField(blank=True, default=IEF.base_model.default_map, null=True, verbose_name='Описание')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='Код')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
                'db_table': '"dct"."abc_dictionary"',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.JSONField(default=IEF.base_model.default_map, verbose_name='Краткое наименование')),
                ('full_name', models.JSONField(blank=True, default=IEF.base_model.default_map, null=True, verbose_name='Краткое наименование')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='Код')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Элемент',
                'verbose_name_plural': 'Элементы',
                'db_table': '"dct"."element"',
            },
        ),
        migrations.CreateModel(
            name='ElementHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp', models.JSONField(blank=True, null=True, verbose_name='Слепок')),
                ('action', models.CharField(blank=True, max_length=128, null=True, verbose_name='Действие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'История элемента',
                'verbose_name_plural': 'История элементов',
                'db_table': '"dct"."element_history"',
            },
        ),
        migrations.CreateModel(
            name='ElementIndicatorValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_int', models.IntegerField(blank=True, null=True, verbose_name='Целое число')),
                ('value_str', models.CharField(blank=True, max_length=255, null=True, verbose_name='Строка')),
                ('value_text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('value_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время')),
                ('value_bool', models.BooleanField(blank=True, null=True, verbose_name='Логическое значение')),
                ('value_reference', models.PositiveIntegerField(blank=True, null=True, verbose_name='Внешний ключ')),
                ('index_sort', models.PositiveIntegerField(blank=True, unique=True, verbose_name='Индекс сортировки')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'Значение инициатора',
                'verbose_name_plural': 'Значение индикаторов',
                'db_table': '"dct"."indicator_value"',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=IEF.base_model.default_map, verbose_name='Наименование')),
                ('description', models.JSONField(blank=True, default=IEF.base_model.default_map, null=True, verbose_name='Описание')),
                ('index_sort', models.PositiveIntegerField(blank=True, unique=True, verbose_name='Индекс сортировки')),
                ('code', models.CharField(max_length=128, unique=True, verbose_name='Код')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Активный')),
                ('type_value', models.CharField(choices=[('str', 'string'), ('int', 'integer'), ('float', 'float'), ('bool', 'boolean'), ('list', 'list'), ('datetime', 'datetime'), ('date', 'date'), ('time', 'time'), ('text', 'text'), ('file', 'file'), ('enum', 'enum'), ('dct', 'dictionary'), ('dcm', 'document'), ('calc', 'calculate')], default='str', max_length=64, verbose_name='Тип')),
                ('type_extend', models.CharField(blank=True, max_length=128, null=True, verbose_name='Тип расширения')),
            ],
            options={
                'verbose_name': 'Индикатор',
                'verbose_name_plural': 'Индикаторы',
                'db_table': '"dct"."indicator"',
            },
        ),
    ]
