# Generated by Django 5.0.3 on 2024-09-10 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='abcdictionary',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='element',
            name='abc_dictionary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.abcdictionary', verbose_name='Справочник'),
        ),
        migrations.AddField(
            model_name='element',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='element', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='element',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='dictionaries.element', verbose_name='Родительский элемент'),
        ),
        migrations.AddField(
            model_name='elementhistory',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='elementhistory',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='element_history', to='dictionaries.element', verbose_name='Элемент'),
        ),
        migrations.AddField(
            model_name='elementindicatorvalue',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='elementindicatorvalue',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_value', to='dictionaries.element', verbose_name='Элемент'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='abc_dictionary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator', to='dictionaries.abcdictionary', verbose_name='Справочник'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='dictionaries.abcdictionary', verbose_name='Внешний ключ'),
        ),
        migrations.AddField(
            model_name='elementindicatorvalue',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_value', to='dictionaries.indicator', verbose_name='Показатель'),
        ),
    ]
