upstream backend {
	server backend:8000;
}

server {
	listen 1337;

	location /api/ {
		proxy_pass http://backend;
	}
	location /admin/ {
	    proxy_pass http://backend;
	}

	location /static/ {
		root /backend;
	}
	location /templates/ {
	    root /templates;
	}

	location / {
		root /var/www/frontend/dist;
		try_files $uri $uri/ /index.html;
	}
}
